apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spiderslab-site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spiderslab-site
    spec:
      containers:
      - name: spiderslab-site
        image: ashmna/spiderslab-site
