apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spiderslab-site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spiderslab-site
    spec:
      containers:
      - name: spiderslab-site
        image: ashmna/spiderslab-site
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
#        volumeMounts:
#        - mountPath: /usr/src/app/data
#          name: pick-data
#      volumes:
#      - name: pick-data
#        gcePersistentDisk:
#          pdName: pick-data
#          fsType: ext4
