apiVersion: v1
kind: Service
metadata:
  name: spiderslab-site
  labels:
    app: spiderslab-site
spec:
  type: LoadBalancer
  selector:
    app: spiderslab-site
  ports:
    - port: 80
      targetPort: 3001
