apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pick-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick-front
    spec:
      containers:
      - name: pick-front
        image: ashmna/pick-front
