apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pick-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick-front
    spec:
      containers:
      - name: pick-front
        image: ashmna/pick-front
        env:
        - name: MONGODB_NAME
          value: pick
        - name: MONGODB_HOST
          value: mongo
        - name: MONGODB_PORT
          value: 27017
        - name: MONGODB_USERNAME
          value: ****************
        - name: MONGODB_PASSWORD
          value: ****************
