apiVersion: v1
kind: Service
metadata:
  name: pick-front
  labels:
    app: pick-front
spec:
#  type: LoadBalancer
  type: NodePort
  selector:
    app: pick-front
  ports:
    - port: 80
      targetPort: 80
