apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pick
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick
    spec:
      containers:
      - name: pick
        image: ashmna/pick
