apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pick
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick
    spec:
      containers:
      - name: pick
        image: ashmna/pick
        imagePullPolicy: Always
        env:
        - name: MONGODB_NAME
          value: "pick"
        - name: MONGODB_HOST
          value: "mongo"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "pick"
        - name: MONGODB_PASSWORD
          value: "6B87V0cF4syl8jd1Qlw5RihXJb3ZyMPP"
        volumeMounts:
        - mountPath: /pick/data
          name: pick-data
        - mountPath: /pick/model
          name: pick-model
      volumes:
      - name: pick-data
        gcePersistentDisk:
          pdName: pick-data
          fsType: ext4
      - name: pick-model
        gcePersistentDisk:
          pdName: pick-model
          fsType: ext4
