apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pick
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick
    spec:
      containers:
      - name: pick
        image: ashmna/pick
        env:
        - name: MONGODB_NAME
          value: "pick"
        - name: MONGODB_HOST
          value: "mongo"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "********"
        - name: MONGODB_PASSWORD
          value: "********"
